apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: dev-common-sharing
  namespace: api
  annotations:
    fluxcd.io/automated: "false"
    repository.fluxcd.io/chart-image: image.path
    registry.fluxcd.io/chart-image: image.registry
    tag.fluxcd.io/chart-image: image.tag
    filter.fluxcd.io/chart-image: 'regexp:^([0-9]+\.[0-9]+\.[0-9]+-[0-9]+)$'
    registry.fluxcd.io/migrationscript: imageMigrationScript.registry
    repository.fluxcd.io/migrationscript: imageMigrationScript.path
    tag.fluxcd.io/migrationscript: imageMigrationScript.tag
    filter.fluxcd.io/migrationscript: 'glob:2.0.2-*'
    helm.fluxcd.io/migrate: "true"
spec:
  helmVersion: v3
  releaseName: dev-common-sharing
  maxHistory: 3
  chart:
    repository: "https://artifactory.datapwn.com/artifactory/tlnd-helm-dev"
    name: common-sharing
    version: 3.1.1
  values:
    image:
      registry: "artifactory.datapwn.com/tlnd-docker-dev"
      path: "talend/common/sharing"
      tag: "444"
      pullPolicy: "IfNotPresent"
    imageMigrationScript:
      registry: "artifactory.datapwn.com"
      path: "tlnd-docker-dev/talend/common/tsbi/centos-base"
      tag: 2.0.2-20200519092346
    launchDarklyClientSideId: 5e7b59a239b9b207cbdfc94d
    launchDarklySdkKey: ENCRYPTED_VALUE
    log:
      loggingLayout: TEXT
    probes:
      liveness:
        initialDelaySeconds: 120
        periodSeconds: 15
        timeoutSeconds: 5
        failureThreshold: 10
      readiness:
        initialDelaySeconds: 120
        periodSeconds: 10
        timeoutSeconds: 5
        successThreshold: 1
        failureThreshold: 3
    replicaCount: 1
    hpa:
      cpu: 100
    resources:
      limits:
        cpu: 1000m
        memory: 1024Mi
      requests:
        cpu: 250m
        memory: 512Mi
    ingress:
      enabled: true
      host: "sharing.api.dev.datapwn.com"
    applicationSecret: "Y:7<xW>`rmNA]VX;[DoFaSc=1<K5Q83^Zc65<HE/5j<hXiZIf0CBm:G3zt2vPWf["
    iamIdpClientId: "P9nZLywBU2CAJ"
    iamIdpClientSecret: "secret"
    tdpJwtSignature: "Nothing is real"
    # Disable monitoring
    monitoring:
      enabled: false
    initdb:
      enabled: true
    sharedDB:
      enabled: true
      passwordSecret: "password"
    tpsvcConfigUrl: "http://tpsvc-config"
    tpsvcIamoidcUrl: "http://tpsvc-idp/oidc"
    tpsvcIamscimUrl: "http://tpsvc-scim/scim"
    minio:
      client:
        proxy:
          host: tdc-talend-infra-minio
        accessKey: minio-access-key
        secret: minio-secret-key
        bucket: tdc-dev
        basePath: repositories
        region: us-east-1
        dumpSubFolder: sharing/dumps
